### ISSUE TITLE
Add a way for admins to log in to other orgs without having a user

### ISSUE THREAD

**Issue by JL102** [FIRSTTeam102/ScoringApp-Serverless#62]
Idea:
- During org creation, automatically create a hidden "Scoutradioz Admin" (or "scoutradioz_admin") user, similar to "default_user". 
- In the admin index page (or the orgs management page), add a button to switch to that Scoutradioz Admin user in any org.
- Requires a password input any time you wish to do it

This code will have to be pretty bulletproof, so before merging, I'll ask the other devs to review it.

**Comment by JL102** [comment]
Code is working, but I'd like it to be reviewed before merging. Don't want any mistakes to slip through.

**Comment by JL102** [comment]
To test on your local system:
1. Create a new org in the new orgs management page, with a dummy org_key, nickname, and default password
It'll then auto create two new users for the org: default_user and scoutradioz_admin.
2. In MongoDB, go to the users col & search for the users under the new org_key you made
3. Hover over scoutradioz_admin & hit Clone document
4. Edit the org_key to be one of the existing orgs in the DB (frc102, frc852, frc8024, and demo)
5. hit Insert, then repeat steps 2 & 3 for the other orgs
6. [Calum only] if you are testing it, you'll have to set your own user's role_key to global_admin first
7. Back in the Orgs Management page, you should now be able to "Log in to X as Scoutradioz Admin" after entering your password.

**Comment by caburum** [comment]
I've tested it out and it seems to be working well, I've also read through the code and I don't see any way that someone could abuse it.

The only annoyance that I have is that after you login to another org, you can't switch to another org again using it or easily go back to your main account without relogging in. I'm not sure if blocking switching from one SR admin to another was intentional, as in the code you check that `user.password !== 'disabled'` as a requirement for switching.

**Comment by JL102** [comment]
hmm...
It was intentional, because I was trying to be over-careful with preventing non admins from accessing the feature. But if we're confident that it's impossible to log in as scoutradioz_admin without being properly authenticated, it's probably a good idea to remove that extra check. I agree that it's pretty annoying.
